### ISSUE TITLE
Verify NavX ability

### ISSUE THREAD

**Issue by juliaschatz** [GOFIRST-Robotics/NASA-RMC-2020-NorthstarRobotics#11]
Verify that the data we're getting from the navx is correct. Measure variance and covariance.

**Comment by JWCS** [comment]
@Andidy Did you still want to even use the navx this year? There was initial discussion on moving away from it?

**Comment by juliaschatz** [comment]
Implemented in https://github.com/GOFIRST-Robotics/navXTimeSync/pull/2
