### ISSUE TITLE
Remove .catkin_tools

### ISSUE THREAD

**Issue by JWCS** [GOFIRST-Robotics/NASA-RMC-2020-NorthstarRobotics#15]
Related to SMACH, I think, when Minyoung added the state machine code?

**Comment by libBAS** [comment]
Where is Minyoung's state machine code?

**Comment by libBAS** [comment]
https://github.com/GOFIRST-Robotics/NASA-RMC-2019-NorthstarRobotics/tree/master/src/bigrdigr_navigation/src
