### ISSUE TITLE
Reformat project to individual subsystems

### ISSUE THREAD

**Issue by juliaschatz** [GOFIRST-Robotics/NASA-RMC-2020-NorthstarRobotics#3]
Currently, the entire robot works by sending CAN messages to the Danfoss with directions for individual motors. This scales poorly, especially as we approach automation. 
I propose that we split up subsystem control into individual ROS nodes. Each node will:
- Own a simple FSM
- Accept high-level command messages
- Send CAN messages with motor commands based on state and received commands
- Respond to lower-level messages and sensor input

Proposed nodes based on ROVR:
- Drivetrain (accept Twist messages)
- Bucket wheel / Transfer Conveyor (accept command messages to begin digging, stop digging, move down, move to top, etc) (manages motors and sensors to keep digger level)
- Holding conveyor (accept command messages to sift, hold, dump, etc)

**Comment by JWCS** [comment]
I like your thoughts, more of this is necessary. Most immediately, what this is pointing to is a higher-level topology and feature set design meeting. I can't speak for Matt/Molly/Andrew, the last of whom is specifically going to manage the low level control, given an agreed-upon can-spec and feature set. 
Just like the ME team first trains, identifies the problems, brainstorms solutions, consolidates into subteams on major subsection boundaries, and collaboratively design both system-level and subsection-level interfacing requirements, you can expect this flow to persist on these areas too. 
Just to give you a heads up on how this issue/enhancement will progress.

**Comment by juliaschatz** [comment]
Most of this is probably going to be inside the STM32. As that project gets more mature we'll adapt the current CAN protocol to abstract subsystem control.

**Comment by JWCS** [comment]
The gist of low-level subsystem control, is that within a continuous loop (in RT system, it gets cut short if too long, so CONSISTENCY is the key value), there is a global set of variables for state, updated by IO, and each subsystem runs an update function on that state, running feedback-controlled actuations. 
In this project, the line (between high-level/slow/temporarily-failable computer and low-level RT controller (note diff btwn computer and controller)), is probably best kept at the point where when the desired mechanical state-objective of the subsystem is known (drive straight, drive in 30 deg bezier curve, do this feed rate of lift-digging), that decision is sent to the controller. Whether this is in simulation with ros (ros msg interface) or canbus (hardware spec). 
In industry, past production stage, it is all on the "controller", in (kindof) single file loop - the path planning/processing/sensor fusion (with dedicated CV/lidar processors)), which is what we're moving to rn.

**Comment by juliaschatz** [comment]
This got turned into the RT control code.
