### ISSUE TITLE
Create or find node that merges pointcloud messages

### ISSUE THREAD

**Issue by juliaschatz** [GOFIRST-Robotics/NASA-RMC-2020-NorthstarRobotics#49]
This should be pretty simple to write, unless it already exists somewhere? I couldn't find something like I wanted.

**Comment by JWCS** [comment]
So, I’m going to say something that is technically right, but prob not appropriate for what you’re trying to do. 
Pointcloud _Registration_ through ICP are the buzzwords to do pointcloud merging. 
I also don’t think that’s what you want/need should do. 

What’re you trying to do? Why do the msgs have to be combined? Where are they going?

**Comment by juliaschatz** [comment]
I don't think we want registration. What I want to do is to combine the two so that the pointcloud_to_laserscan node sees both of them. It's just occurred to me that we could combine the laserscan messages as well. But is it even necessary for them to be combined? Or can move_base use two laserscan topics?

**Comment by JWCS** [comment]
Ding ding ding!
For each lidar/stereo ptcld, convert to lasers can, and feed to move base.
(Might not even need to convert, I think move base should be fine with
pointcloud inputs. It will handle the merging of each input msg).
The receiving node always handles the merging data that it subscribed to.
