### ISSUE TITLE
Cameras are attached in inconsistent orders

### ISSUE THREAD

**Issue by juliaschatz** [GOFIRST-Robotics/NASA-RMC-2020-NorthstarRobotics#6]
If each one is attached to a consistent port, it should be trivial to write udev rules to put them in order: 
https://superuser.com/questions/485617/writing-usb-udev-rules-based-on-vendorid-productid-usb-bus-information

**Comment by juliaschatz** [comment]
Haha okay it is not trivial.
For some reason (I've tried almost everything) udev won't match both the KERNELS tag and anything else.
So we can get a symlink based on where the device is attached using
`ACTION=="add", KERNELS=="1-1:1.0", SYMLINK+="pseye0"`
but can't filter based on the device. If we want to just match the USB hub that they're directly on, that works too. If everything is plugged into the correct USB port every time, this shouldn't be a problem.

**Comment by juliaschatz** [comment]
This should be done for the Realsense cameras as well

**Comment by juliaschatz** [comment]
Extend to Decawaves and IMUs. This can all be done using the same kind of thing. You can find the KERNELS directive by running `udevadm info -a /dev/XXXX` and looking for the topmost KERNELS line.

**Comment by JWCS** [comment]
For the record, we (Matt) did know that there was no way to tell apart the pseye's apart from where plugged in (I think). The others, I think, may be individual - the realsenses definitely are.
